
CREATE TABLE CAMEL_TEST ( 
  ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  ENTITY_ID BIGINT,
  LABEL VARCHAR(200),
  LOCATION VARCHAR(5),
  CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO CAMEL_TEST (ENTITY_ID, LABEL,LOCATION) VALUES 
    (10,'SOME LABEL', 'GB'),(20,'TWENTY LABEL', 'IE'), (30,'THIRTY LABEL', 'IE');